### ISSUE TITLE
Anything that needs to be worked on?

### ISSUE THREAD

**Issue by logotie** [xgi/houdoku#1]
Hiya, would there please be any bugs or enhancements that you have planned?

Would definitely like to contribute some code :)

**Comment by xgi** [comment]
I just made a few issues for some things I had in my backlog, so feel free to work on them if you like (but don't feel obligated to). Just assign yourself or leave a comment if you plan on working on one.

Otherwise, if there are websites you want added to the client, you can write a plugin in [houdoku-plugins](https://github.com/xgi/houdoku-plugins). There's no guide for this yet, but for the most part you could just copy how the other ones work. The interface is [here](https://github.com/xgi/houdoku/blob/master/src/main/java/com/faltro/houdoku/plugins/content/ContentSource.java).

And obviously feel free to work on any bugs/features you think of.

Thanks!
