### ISSUE TITLE
After opening another chapter pages start to lag

### ISSUE THREAD

**Issue by cmlimm** [xgi/houdoku#107]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.8.0

### Operating system

Windows 10

### Steps to reproduce

1. Download manga from https://nyaa.si/view/1494208 or [my Google Drive](https://drive.google.com/file/d/1Lf5p32DHppwzw8oxVhYMOWVObJEP_ydF/view?usp=sharing)
2. Import manga from folder
3. Open any chapter
4. Close chapter
5. Open another chapter

### Expected behavior

Pages behave normally

### Actual behavior

Pages start to "blink", it changes from page from previously open chapter to current

### Log files

[main.log](https://github.com/xgi/houdoku/files/8245954/main.log)
[renderer.log](https://github.com/xgi/houdoku/files/8245955/renderer.log)

### Additional information

I tried to reproduce this behavior with some other manga, but this bug didn't appear :( 
I guess there is something wrong with these particular files? Are they too big maybe?

**Comment by xgi** [comment]
Thanks for the report, I was able to reproduce this.

To give some insight, the reason this is happening is linked to how Houdoku currently handles archives (zip/cbz/rar/cbr). Currently it extracts pages from the archive in-memory, and basically inserts them onto the viewer. This already has a few caveats (it's rather slow in general), but it also led to the bug here where it continues extracting from one chapter even when you switch to viewing another chapter. This is more likely to happen if there are a lot of pages.

I think what I'll do is implement a cache/temp folder mechanism that the pages get extracted to for the viewer, which would fix this issue and probably make it work better in general. However that's a pretty substantial feature, so it'll take some time for me to do.

In the meantime, if you're interested/willing, you can extract your `.cbz` files yourself. e.g. your folder structure would look like:
```
Toilet-bound Hanako-kun
  - Toilet-bound Hanako-kun v01
     - something p001.jpg
     - something p002.jpg
     - ...
  - Toilet-bound Hanako-kun v02
     - something p001.jpg
     - something p002.jpg
     - ...
  - ... 
```

(note that `cbz` is exactly the same as `zip`)

**Comment by cmlimm** [comment]
Thanks for the insight and for the way to temporarily fix the issue!

**Comment by xgi** [comment]
With #126 I implemented the temp folder mechanism described earlier; reading from archives is now significantly faster and won't create the "blinking" bug described here. Of course, archived chapters are still inherently a bit slower, but that's the speed vs. space tradeoff.

Thanks!
