### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by dragow0lf** [xgi/houdoku#119]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.8.1

### Operating system

Windows 10

### Steps to reproduce

Just use the app as normal

### Expected behavior

It should work as normal

### Actual behavior

You randomly get a javascript error that turns everything black, you essentially can't see anything and you cant interact with anything (don't know if I am actually able to interact with stuff as I can't see anything, however the cursor doesn't change no matter where I take it, so concluding it doesn't interact with anything)

### Log files

[main.log](https://github.com/xgi/houdoku/files/8407655/main.log)
[renderer.log](https://github.com/xgi/houdoku/files/8407657/renderer.log)

### Additional information

This happens randomly, and the only way to fix it from what I've seen is to close and reopen the app
There is also another java script error that happens randomly as well, but that doesn't affect anything
I like an idiot didn't actually note down the java script error details, however I do remember reading the word connection or timeout in one or both of them. Since I can't recreate this bug at my will, can't really confirm

**Comment by xgi** [comment]
Thanks for the logs -- the main issue here was that some requests to an extension website (MangaDex) were failing in a way that Houdoku didn't handle. I've updated the client logic with #123 to avoid crashing in that case.

I think specifically this was because of rate-limiting on MangaDex's side -- Houdoku complies with the general rate limit, but MangaDex can update their rate limit dynamically. Regardless, this shouldn't cause a crash in Houdoku anymore.
