### ISSUE TITLE
UI elements absurdly small

### ISSUE THREAD

**Issue by DeadAmericana** [xgi/houdoku#270]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

v2.12.2

### Operating system

Windows 10

### Steps to reproduce

![Screenshot 2023-04-25 232100](https://user-images.githubusercontent.com/101665235/234469250-25876717-4c7c-466a-b9b8-950e11b448fd.png)
![Screenshot 2023-04-25 232041](https://user-images.githubusercontent.com/101665235/234469253-0c17962f-9098-4264-af12-97ebe3a58c09.png)
![Screenshot 2023-04-25 232014](https://user-images.githubusercontent.com/101665235/234469256-f62d8250-3b9c-4b5d-b41b-e84d2268f0f7.png)

### Expected behavior

UI Should look normal and scale 

### Actual behavior

Instead looks small

### Additional information (optional)

UI elements are miniscule since one of the most recent updates with the exception of cover art which is still fine for some reason. The reading experience is still flawless and scales appropriately.

**Comment by Blacklands** [comment]
This is closed as completed, but it's still happening for me. Seems to be an issue with scaling on Windows. I'm on 150% scaling on a tablet and the UI elements are tiny. The actual images when reading are fine, it's just the UI.

**Comment by annieice** [comment]
welp it's 2026 and i have the exact same issue...

**Comment by WilliShakes** [comment]
From what I understood, both Houdoku's UI and the images rendering are affected by windows scaling. 
This resulted in images being zoomed according to windows scaling (which made it impossible to haves images rendered 1:1) (https://github.com/xgi/houdoku/pull/308). 
Xgi's fix (https://github.com/xgi/houdoku/commit/c301a101e7489642854571f2be3349196f7e1a43) forced Houdoku's scale to 1. Which (since both Houdoku's UI and the images rendering are affected by windows scaling) prevented the UI from scaling.
So, until it's been correctly fixed, if you want to have the UI scaled with windows scaling you'll need to use Izkda "fix"(removal of the force scale to 1) ([Izkda:master](https://github.com/Izkda/houdoku/tree/master)).
