### ISSUE TITLE
no text visible in chapter list view

### ISSUE THREAD

**Issue by Jabbawingo** [xgi/houdoku#286]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.13.0

### Operating system

win11

### Steps to reproduce

click on a manga in the library

### Expected behavior

it should have the chapter name

### Actual behavior

no text is visible

**Comment by Jabbawingo** [comment]
![image](https://github.com/xgi/houdoku/assets/46444452/a8f6be45-dacd-408c-889e-fd1c7f24fc6a)

**Comment by ismaelcompsci** [comment]
looks like an issue with the extension `mangasee` same thing is happening with `mangalife` since they use the `nepClient`. I'm not sure if they used `chapterName` before but it's always `null` in the `getChapters` method.

**Comment by xgi** [comment]
Updated Mangasee & Mangalife extensions with https://github.com/xgi/houdoku-extensions/commit/df6161cde4957b1302182feffa87ff2390253605. This wasn't really incorrect because those sources don't provide actual titles, but it'll now show the prefix from the source. e.g.
- "Chapter XYZ" for https://mangasee123.com/manga/Boku-Wa-Mari-No-Naka
- "Stage XYZ" for https://mangasee123.com/manga/Gacha-Wo-Mawashite-Nakama

**Comment by Jabbawingo** [comment]
Thanks!
