### ISSUE TITLE
Have a choice of image format for downloads

### ISSUE THREAD

**Issue by FBSANAKONDA** [xgi/houdoku#334]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

I want to request the feature to make it possible to set a desired image format instead of the default compressed jpg, because png is just better. I hope this will get attention from people, because jpg is a bad and lossy format.

**Comment by xgi** [comment]
Houdoku downloads whichever format the source website uses, so there's nothing Houdoku can do differently here. If the website uses lossy jpegs, that's what will get downloaded. Converting it to a png on Houdoku's side won't help anything because it's already been compressed.

If you notice the downloaded image is somehow worse quality than what's on the website, please open an issue in this repo with the name of the website/source: https://github.com/xgi/tiyo
