### ISSUE TITLE
Covers of manga not showing in the library

### ISSUE THREAD

**Issue by BaccanoMob** [xgi/houdoku#41]
The cover icons does not show up for me even after refreshing. 
First was from catmanga (online source)
Second was from local (just accidentally forgot to choose an cover)
Third also from local but chose a cover.

![image](https://user-images.githubusercontent.com/82655889/120895807-f7952f80-c61e-11eb-8b8e-4a2074feaca5.png)

but works fine when opening a series
![image](https://user-images.githubusercontent.com/82655889/120895905-5e1a4d80-c61f-11eb-8a03-4f12ce5d72bf.png)

Is there any specifications for choosing a cover?

**Comment by xgi** [comment]
There have been tons of changes to extensions (including the local import) since the last release, so it's likely this has already been resolved - I haven't personally seen any missing covers during testing in a while, except when the source doesn't have one.

I'm going to close this issue since I don't really have a way to track whether it's fixed, but if you continue to notice this after the next release feel free to make an issue in the [extensions repo](https://github.com/xgi/houdoku-extensions).
