### ISSUE TITLE
[Feature Request]: Integrate to Anilist | Add Discord Rich Presence

### ISSUE THREAD

**Issue by maisans-maid** [xgi/houdoku#47]
Add option to sign in to anilist to automatically update our profile for every chapter we read.
For context, [Taiga](https://taiga.moe/) allows users to manage their Anilist profile automatically while watching a series.

Also, add option to *enable/disable* rich presence for discord.
[Taiga](https://taiga.moe/) does this aswell.

**Comment by xgi** [comment]
I've added tracker/AniList support with #49. There are more details/screenshots in that PR if you're interested. It's possible to expand this to include other list trackers like Kitsu/MAL/etc, but that probably won't happen soon.

I should be able to support Discord's rich presence, but I'll have to look into it because I don't have much experience with their APIs. Thanks!

**Comment by xgi** [comment]
Discord presence integration added with #51. Can be enabled in the settings, and shows the series/chapter you're reading. Thanks!
