### ISSUE TITLE
NPE when attempting to read added manga

### ISSUE THREAD

**Issue by logotie** [xgi/houdoku#8]
1.  Add 'Birdy the might evolution' from 'MangaHasu' to your library
2.  Open and attempt to read chapter 24.
3.  In intellij, a NPE is generated.

Exception in thread "loadPage_MangaHasu <mangahasu.se>_/birdy-the-mighty-evolution/vol-3-chapter-24-accidental-summer-3-c687989.html0" java.lang.NullPointerException
	at com.faltro.houdoku.plugins.content.MangaHasu.image(MangaHasu.java:144)
	at com.faltro.houdoku.util.runnable.LoadPageRunnable.run(LoadPageRunnable.java:51)
	at java.lang.Thread.run(Thread.java:748)

**Comment by logotie** [comment]
I add these issues so I can come back to them

**Comment by logotie** [comment]
I think maybe we should display an error when a NPE is generated on attempting to open a manga chapter?

Or maybe on adding a series, we go through all the chapters to check whether any of them point to Null before adding?  However this would slow down the app considerably?

**Comment by xgi** [comment]
Plugins are currently able to throw a ContentUnavailableException which are handled pretty well in the client. I've added this to the MangaHasu plugin so it should now display the error as necessary (I also noticed that most of that site is inaccessible, but that's another issue). Other plugins may need this too.

I don't really want to handle NullPointer specifically, though, because that's a development problem on the plugin side which should always be wrapped in a custom exception (like ContentUnavailableException) which we do handle.

I also don't want to scan every chapter when adding the series since it would be very slow, and I think showing an error per-chapter is acceptable UX.
